#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#include <stdlib.h>
#include <string.h>

// All Cocoa entry points are called on Tauri's main thread.
long copyy_change_count(void) { return NSPasteboard.generalPasteboard.changeCount; }
char *copyy_read_content(void) {
    @autoreleasepool {
        NSPasteboard *pb = NSPasteboard.generalPasteboard;
        for (NSString *type in @[@"org.nspasteboard.ConcealedType", @"org.nspasteboard.TransientType", @"org.nspasteboard.AutoGeneratedType", @"com.agilebits.onepassword"]) {
            if ([pb.types containsObject:type]) return NULL;
        }
        NSDictionary *payload = nil;
        NSArray<NSURL *> *files = [pb readObjectsForClasses:@[NSURL.class] options:@{NSPasteboardURLReadingFileURLsOnlyKey:@YES}];
        if (files.count) {
            NSMutableArray *urls = [NSMutableArray array];
            NSMutableArray *names = [NSMutableArray array];
            for (NSURL *file in files) { [urls addObject:file.absoluteString]; [names addObject:file.lastPathComponent ?: file.path]; }
            NSData *json = [NSJSONSerialization dataWithJSONObject:urls options:0 error:nil];
            payload = @{ @"kind":@"files", @"content":[[NSString alloc] initWithData:json encoding:NSUTF8StringEncoding], @"preview":[names componentsJoinedByString:@"\n"] };
        } else if ([pb.types containsObject:NSPasteboardTypePNG] || [pb.types containsObject:NSPasteboardTypeTIFF]) {
            NSData *data = [pb dataForType:NSPasteboardTypePNG] ?: [pb dataForType:NSPasteboardTypeTIFF];
            if (!data || data.length > 16*1024*1024) return NULL;
            NSBitmapImageRep *rep = [NSBitmapImageRep imageRepWithData:data];
            if (!rep || rep.pixelsWide > 10000 || rep.pixelsHigh > 10000 || rep.pixelsWide < 1 || rep.pixelsHigh < 1) return NULL;
            NSData *png = [rep representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
            if (!png || png.length > 16*1024*1024) return NULL;
            CGFloat scale = MIN(1.0, MIN(480.0/rep.pixelsWide, 220.0/rep.pixelsHigh));
            NSInteger w = MAX(1, (NSInteger)(rep.pixelsWide*scale)), h = MAX(1, (NSInteger)(rep.pixelsHigh*scale));
            NSBitmapImageRep *thumb = [[NSBitmapImageRep alloc] initWithBitmapDataPlanes:NULL pixelsWide:w pixelsHigh:h bitsPerSample:8 samplesPerPixel:4 hasAlpha:YES isPlanar:NO colorSpaceName:NSDeviceRGBColorSpace bytesPerRow:0 bitsPerPixel:0];
            if (!thumb) return NULL;
            [NSGraphicsContext saveGraphicsState];
            NSGraphicsContext.currentContext = [NSGraphicsContext graphicsContextWithBitmapImageRep:thumb];
            NSGraphicsContext.currentContext.imageInterpolation = NSImageInterpolationHigh;
            [rep drawInRect:NSMakeRect(0,0,w,h)];
            [NSGraphicsContext restoreGraphicsState];
            NSData *thumbData = [thumb representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
            payload = @{ @"kind":@"image", @"content":[png base64EncodedStringWithOptions:0], @"preview":[thumbData base64EncodedStringWithOptions:0], @"width":@(rep.pixelsWide), @"height":@(rep.pixelsHigh) };
        } else {
            NSString *value = [pb stringForType:NSPasteboardTypeString];
            if (!value || [value lengthOfBytesUsingEncoding:NSUTF8StringEncoding] > 1024*1024) return NULL;
            NSString *preview = value;
            if (value.length > 1200) preview = [value substringWithRange:[value rangeOfComposedCharacterSequencesForRange:NSMakeRange(0,1200)]];
            payload = @{ @"kind":@"text", @"content":value, @"preview":preview };
        }
        NSData *json = [NSJSONSerialization dataWithJSONObject:payload options:0 error:nil];
        return json ? strdup([[NSString alloc] initWithData:json encoding:NSUTF8StringEncoding].UTF8String) : NULL;
    }
}
// 1 success, -1 missing file, 0 invalid data. Validate before replacing the clipboard.
int copyy_write_content(const char *json) {
    @autoreleasepool {
        NSData *data = [[NSString stringWithUTF8String:json] dataUsingEncoding:NSUTF8StringEncoding];
        NSDictionary *payload = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
        NSString *kind = payload[@"kind"], *content = payload[@"content"];
        NSPasteboard *pb = NSPasteboard.generalPasteboard;
        if ([kind isEqualToString:@"text"]) {
            [pb clearContents]; return [pb setString:content forType:NSPasteboardTypeString];
        }
        if ([kind isEqualToString:@"image"]) {
            NSData *png = [[NSData alloc] initWithBase64EncodedString:content options:0];
            if (!png) return 0;
            [pb clearContents]; return [pb setData:png forType:NSPasteboardTypePNG];
        }
        if ([kind isEqualToString:@"files"]) {
            NSArray *values = [NSJSONSerialization JSONObjectWithData:[content dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];
            NSMutableArray *urls = [NSMutableArray array];
            for (NSString *value in values) {
                NSURL *url = [NSURL URLWithString:value];
                if (!url.fileURL || ![NSFileManager.defaultManager fileExistsAtPath:url.path]) return -1;
                [urls addObject:url];
            }
            if (!urls.count) return 0;
            [pb clearContents]; return [pb writeObjects:urls];
        }
        return 0;
    }
}
int copyy_frontmost_pid(void) { return NSWorkspace.sharedWorkspace.frontmostApplication.processIdentifier; }
char *copyy_frontmost_name(void) {
    @autoreleasepool { return strdup((NSWorkspace.sharedWorkspace.frontmostApplication.localizedName ?: @"未知应用").UTF8String); }
}
int copyy_activate(int pid) {
    NSRunningApplication *app = [NSRunningApplication runningApplicationWithProcessIdentifier:pid];
    if (!app || app.terminated) return 0;
    if (@available(macOS 14.0, *)) {
        [NSApp yieldActivationToApplication:app];
        return [app activateFromApplication:NSRunningApplication.currentApplication options:0];
    }
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    return [app activateWithOptions:NSApplicationActivateIgnoringOtherApps];
#pragma clang diagnostic pop
}
int copyy_trusted(void) { return AXIsProcessTrusted(); }
void copyy_open_accessibility(void) {
    [NSWorkspace.sharedWorkspace openURL:[NSURL URLWithString:@"x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"]];
}
int copyy_modifiers_released(void) {
    CGEventFlags flags = CGEventSourceFlagsState(kCGEventSourceStateCombinedSessionState);
    return !(flags & (kCGEventFlagMaskCommand | kCGEventFlagMaskShift | kCGEventFlagMaskAlternate | kCGEventFlagMaskControl));
}
int copyy_paste(int target) {
    if (!AXIsProcessTrusted() || copyy_frontmost_pid() != target || !copyy_modifiers_released()) return 0;
    CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStatePrivate);
    if (!source) return 0;
    CGEventRef down = CGEventCreateKeyboardEvent(source, 9, true);
    CGEventRef up = CGEventCreateKeyboardEvent(source, 9, false);
    if (!down || !up) {
        if (down) CFRelease(down);
        if (up) CFRelease(up);
        CFRelease(source);
        return 0;
    }
    CGEventSetFlags(down, kCGEventFlagMaskCommand);
    CGEventSetFlags(up, kCGEventFlagMaskCommand);
    CGEventPost(kCGHIDEventTap, down);
    CGEventPost(kCGHIDEventTap, up);
    CFRelease(down); CFRelease(up); CFRelease(source);
    return 1;
}
void copyy_free(char *value) { free(value); }
